---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--safe]
  - repo: https://github.com/koyeung/ko-poetry-audit-plugin.git
    rev: 0.8.0a1
    hooks:
      - id: poetry-audit
